modLoader="javafml"
loaderVersion="[47,)"
license="LGPL v2.1"
issueTrackerURL=""
[[mods]]
modId="rttgtcore"
version="1.1"
displayName="RTTGTCore"
logoFile="icon.png"
authors="ialdaiaxiariyay"
description='''Reset Time Technology GTCore'''
[[dependencies.rttgtcore]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.rttgtcore]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.rttgtcore]]
modId = "gtceu"
mandatory = true
versionRange = "[1.0.16,)"
ordering = "AFTER"
side = "BOTH"